packages:
  - apps/*
  - config/*
  - infra/*
  - packages/*
  - scripts/*

catalog:
  '@chromatic-com/storybook': ^4.1.1
  '@eslint/eslintrc': ^3
  '@eslint/js': ^9.36.0
  '@next/eslint-plugin-next': ^15.5.0
  '@radix-ui/react-accordion': 1.2.12
  '@radix-ui/react-alert-dialog': 1.1.15
  '@radix-ui/react-aspect-ratio': 1.1.7
  '@radix-ui/react-avatar': 1.1.10
  '@radix-ui/react-checkbox': 1.3.3
  '@radix-ui/react-collapsible': 1.1.12
  '@radix-ui/react-context-menu': 2.2.16
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-hover-card': 1.1.15
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-menubar': 1.1.16
  '@radix-ui/react-navigation-menu': 1.2.14
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-progress': 1.1.7
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-scroll-area': 1.2.10
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-separator': 1.1.7
  '@radix-ui/react-slider': 1.3.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': 1.2.8
  '@storybook/addon-a11y': 9.1.10
  '@storybook/addon-docs': ^9.1.10
  '@storybook/addon-styling-webpack': ^2.0.0
  '@storybook/addon-vitest': 9.1.10
  '@storybook/nextjs': ^9.1.10
  '@storybook/nextjs-vite': ^9.1.10
  '@storybook/react-vite': ^9.1.10
  '@tailwindcss/cli': 4.1.16
  '@tailwindcss/postcss': 4.1.16
  '@tailwindcss/vite': ^4.1.14
  '@turbo/gen': ^2.5.0
  '@types/node': ^24
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5.0.4
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  autoprefixer: 10.4.21
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  embla-carousel-react: 8.6.0
  eslint: ^9
  eslint-config-next: 15.5.4
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.22
  eslint-plugin-storybook: ^9.1.10
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.4.0
  input-otp: 1.4.2
  lucide-react: 0.545.0
  next: canary
  playwright: ^1.56.0
  postcss: ^8.5.6
  prettier: ^3.6.2
  react: latest
  react-day-picker: ^9.11.1
  react-dom: latest
  react-resizable-panels: 3.0.6
  recharts: 2.15.4
  storybook: ^9.1.10
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.16
  turbo: canary
  tw-animate-css: ^1.4.0
  typescript: ^5
  typescript-eslint: ^8.45.0
  vaul: 1.1.2
  vite: npm:rolldown-vite@7.1.14
  vitest: ^3.2.4

catalogMode: strict

enableGlobalVirtualStore: true
